### ISSUE TITLE
Opening .bin files doesn't work

### ISSUE THREAD

**Issue by jochem-waque** [autergame/BinReaderGUI#2]
I seem to be unable to open any .bin files using the latest version.

After running `GetOpenFileNameA` on line 347, the file path is in `openFile_temp` (line 337). On line 349, the first character of `openFile` is checked, but the contents of `openFile` can still be 0 at this point. Moving the `memcpy` on line 351 outside of the if-statement seems to fix the issue.

https://github.com/autergame/BinReaderGUI/blob/4e1d0bdcf0b08cf64645bd44b45b2efd7974f1b1/BinReaderGUI/main.cpp#L335-L352

**Comment by fernpi** [comment]
I should have put openFile_temp instead of openFile on line 349, but i am programming rust in linux now and i dont have visual studio anymore.

**Comment by jochem-waque** [comment]
If you want I can make the change and make a PR? In the process I might also update the MSVC toolset to v143 (from v142) as that's the latest version and what I have installed currently

**Comment by fernpi** [comment]
And please build the x86 and x64 releases

**Comment by fernpi** [comment]
Fixed: https://github.com/autergame/BinReaderGUI/commit/ad0ff5af09fdddb0f40f31d638fe1b9ceee850d3
